"""Shared constants."""

SESSION_SLEEPING = "sleeping"
SESSION_REPLY_RATE = "reply_rate"
SESSION_HISTORY_VERSION = "history_version"
SESSION_LAST_SUMMARY_VERSION = "last_summary_version"
SESSION_SUMMARY_COOLDOWN_UNTIL = "summary_cooldown_until"

CFG_DEFAULT_REPLY_RATE = "default_reply_rate"
CFG_BLOCKED_GROUPS = "blocked_groups"
CFG_BLOCKED_USERS = "blocked_users"
CFG_ENABLE_SUMMARY_MEMORY = "enable_summary_memory"
CFG_SUMMARY_ONLY_GROUP = "summary_only_group"
CFG_SUMMARY_TRIGGER_ROUNDS = "summary_trigger_rounds"
CFG_SUMMARY_KEEP_RECENT_MESSAGES = "summary_keep_recent_messages"
CFG_SUMMARY_COOLDOWN_SECONDS = "summary_cooldown_seconds"
CFG_SUMMARY_MIN_NEW_MESSAGES = "summary_min_new_messages"
CFG_ENABLE_TOOLS = "enable_tools"
CFG_PROMPT_BASE = "prompt_base"
CFG_PROMPT_LOGIC_PRIVATE = "prompt_logic_private"
CFG_PROMPT_LOGIC_AT_ME = "prompt_logic_at_me"
CFG_PROMPT_LOGIC_POKE = "prompt_logic_poke"
CFG_PROMPT_LOGIC_GROUP = "prompt_logic_group"
CFG_PROMPT_SUMMARY_SYSTEM = "prompt_summary_system"
